// Equipement outputs

#IFDEF NOT __INC_OUTPUTS__ THEN
#DEFINE __INC_OUTPUTS__

//  Input variables that can be configured via the configuration dialog (These are global)
VAR_OUTPUT
   // BUILT_IN
   DOUT_1 : BOOL;
   DOUT_2 : BOOL;
   DOUT_3 : BOOL;
   DOUT_4 : BOOL;
   DOUT_5 : BOOL;
   DOUT_6 : BOOL;
   DOUT_7 : BOOL;
   DOUT_8 : BOOL;
   
   AOUT_1 : INT;
   AOUT_2 : INT;
   AOUT_3 : INT;
   AOUT_4 : INT;
   
   LED_1 : BOOL;
   LED_2 : BOOL;
   LED_3 : BOOL;
   LED_4 : BOOL;
   
   // Pilotage
  

  
END_VAR;



#END_IF